### ISSUE TITLE
using case sensitive file name for TreeModel.h

### ISSUE THREAD

**Issue by tuxx42** [mikispring/H_DbAdmin#1]
```
src/HDbAdminWindow.cpp:39:10: fatal error: qbase/examples/widgets/itemviews/simpletreemodel/TreeModel.h: No such file or directory
 #include "qbase/examples/widgets/itemviews/simpletreemodel/TreeModel.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:715: HDbAdminWindow.o] Error 1

```

The file name is treemodel.h not TreeModel.h. Linux uses case sensitive file systems by default, so this will only build under windows.

**Comment by mikispring** [comment]
Yes, you are right. Feel free to create a pull request or I will fix it directly. 
Thank you.

**Comment by goldenpointer** [comment]
Renamed the file name occurrences. This should fix the issue. 
Remark: Not yet to tested on a Linux machine.
